### ISSUE TITLE
The training data, test data and label files were not found in the hosting university server, can they be uploaded in the repository or tell us from where they can be downloaded?

### ISSUE THREAD

**Issue by nsapkota68** [EklavyaFCB/EMNIST-Kohonen-SOM#1]

**Comment by EklavyaFCB** [comment]
I forget exactly how I unwrapped the data, but you can find it here: https://github.com/aurelienduarte/emnist

Then you have to sort it with sort.py and put the correct path in som.py as explained here: https://github.com/EklavyaFCB/EMNIST-Kohonen-SOM#note

**Comment by nsapkota68** [comment]
Thank you so much.

Nabin

**Comment by nsapkota68** [comment]
[dataset_byclass.txt](https://github.com/EklavyaFCB/EMNIST-Kohonen-SOM/files/5287546/dataset_byclass.txt)

I was able to read the Matlab file, but could not process nested nd array in a file 'dataset_byclass'. I have spent quite a time trying to unwrap it, then sort it, but it seems like it is beyond my skill. Any help is appreciated. I want to use the results in a paper and cite this source. Thank you.

The file attached is the values of the dataset field of dictionary item of the Matlab file dataset_byclass.

**Comment by EklavyaFCB** [comment]
Alright I'll try to sort this tomorrow morning and give it to you asap, I need to update this repo anyway.

**Comment by EklavyaFCB** [comment]
I have updated the instructions, and placed the new .csv files on my google drive.

You just have clone again (or pull), place the data from my GDrive to the correct path as explained [here](https://github.com/EklavyaFCB/EMNIST-Kohonen-SOM#data), and run `som.py`.

Have also added a [cite](https://github.com/EklavyaFCB/EMNIST-Kohonen-SOM#cite) part.

 Let me know if you have any issues now.

For further reading, you can also refer to my [thesis](https://eklavyafcb.github.io/docs/KohonenThesis.pdf).

**Comment by nsapkota68** [comment]
Thank you very much, I could run all the files now. Your thesis is impressive.

**Comment by EklavyaFCB** [comment]
Great! I look forward to reading your paper too someday !

**Comment by EklavyaFCB** [comment]
Did you ever write a paper ?
